### Spring properties
# Service registers under this name
spring:
  application:
    name: account-api-microservice

# Discovery Server Access
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
        defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2222

#tile Info for Field  
tile:
  tileInfo:
    creditAgreementTile:
     - apiName:  BusinessFinancingAPI
       fieldName: releasedLimitAmount,productCode
     - apiName:  ProductAgreementAPI
       fieldName: accountNumber,agreementId
    
    savingTransactionTile:
     - apiName:  SearchAPI
       fieldName: releasedLimitAmount,productCode
     - apiName:  ArrangementAPI
       fieldName: releasedLimitAmount,productCode
       
#tile Info for Field      
tileinformation:
  mapTileInfo:
    creditAgreementTile:
      BusinessFinancingAPI:
        - releasedLimitAmount
        - productCode
      ProductAgreementAPI:
        - accountNumber
        - agreementId
        
    savingTransactionTile:
      gArrangmentAPI:
        - releasedLimitAmount
        - productCode
      gArrengmentSearchAPI:
        - accountNumber
        - agreementId

config:
 persondetail:
  food:
     fruits:
       - mango
       - banana
     vegitables:
       - onion
       - potato
  study:
     school:
       - RVS
       - NPS
     subject:
       - hindi
       - english